### ISSUE TITLE
Error When Run By Flutter v0.8.2

### ISSUE THREAD

**Issue by jonahfang** [boeledi/flutter_reactive_button#1]
![image](https://user-images.githubusercontent.com/16301509/45914098-ae065580-be72-11e8-8b14-b5b6383e420d.png)

**Comment by jonahfang** [comment]
Where are this these images? I must found by self?

**Comment by boeledi** [comment]
Hi jonanfang,

As the main objective of a package sample is to demonstrate the usage of the library, it is normally not a good practice to include "personal" items (such asset images, in this example).  However, for your convenience, I have just put a file (images.zip) which contains the asset images, used in the example.  Please read the "README.md" file, from the image.zip, for further instructions on how to use them.

Otherwise, I have not seen any issue in using the "flutter_reactive_button" package with version 0.8.2 of Flutter.  

Hoping that this will help you.

Regards, 

Didier

**Comment by jonahfang** [comment]
@boeledi Thanks.Your work is great and very helpful to me.
